repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: fix-encoding-pragma
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: trailing-whitespace
      - id: double-quote-string-fixer
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: clippy
      - id: fmt
        args: ["--verbose", "--edition", "2018"]
      - id: cargo-check
        args: ["--verbose"]
