name: Test

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: FULL
      CARGO_TERM_COLOR: always

    steps:
      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          # Add date to the cache to keep it up to date
          key: ${{ matrix.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
            ${{ matrix.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          # Add date to the cache to keep it up to date
          key: ${{ matrix.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
            ${{ matrix.os }}-cargo-index-

      - name: Cache core cargo target
        uses: actions/cache@v3
        with:
          path: target
          # Add date to the cache to keep it up to date
          key: ${{ matrix.os }}-cargo-core-${{ hashFiles('core/**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.os }}-cargo-core-${{ hashFiles('core/**/Cargo.toml') }}
            ${{ matrix.os }}-cargo-core-

      - name: Clippy
        run: |
          cargo clippy --release -- -D clippy::all

      - name: Tests
        run: |
          cargo test --release
